FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/jupyter.txt .

RUN pip install --no-cache-dir -r jupyter.txt

COPY notebooks/ /app/notebooks/
COPY src/ /app/src/
COPY data/ /app/data/

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=vitbiometrics"]
